name: sneaker_collector
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  http: ^1.1.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.24.9
  flutter_driver:
    sdk: flutter
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0
  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/SneakerCollectorLogo.png
    - assets/images/adidas-Ultra-Boost-Disney-Goofy-Product.jpg
    - assets/images/sbdunklow.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo/SneakerCollectorLogo.png