// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-vSE-jstzSVibPkjSS5QBmu2QP_2HJkg',
    appId: '1:730924529450:web:95cbe640405f803e229053',
    messagingSenderId: '730924529450',
    projectId: 'sneakercollector-493ae',
    authDomain: 'sneakercollector-493ae.firebaseapp.com',
    storageBucket: 'sneakercollector-493ae.appspot.com',
    measurementId: 'G-0CEPT2FFBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6E2TEc4MpM-TMPqAYLeNCYO6O_JokHg',
    appId: '1:730924529450:android:02ec0acfd1c993be229053',
    messagingSenderId: '730924529450',
    projectId: 'sneakercollector-493ae',
    storageBucket: 'sneakercollector-493ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvzLfvpoh-6j0XhRgPjhPqSP3QWgSkhE',
    appId: '1:730924529450:ios:8273dd6a16872712229053',
    messagingSenderId: '730924529450',
    projectId: 'sneakercollector-493ae',
    storageBucket: 'sneakercollector-493ae.appspot.com',
    iosBundleId: 'com.example.sneakerCollector',
  );
}